### ISSUE TITLE
Buildings incorrectly missing HVAC systems

### ISSUE THREAD

**Issue by JLReyna** [NREL/OpenStudio-BuildStock#434] opened 2020-04-03 17:26 UTC
During troubleshooting an LA100 issue, we discovered an issue where buildings that have been assigned `Option=Electricity` in `Heating Fuel.tsv` are being assigned `Option=None` in `HVAC System Heating Electricity.tsv` even though the dependencies in specify that `Dependency=HVAC System Is Heat Pump` is No and `Dependency=HVAC System Is Shared` is `Neither Shared` or `Only Cooling Shared`. Essentially, this means our fraction of buildings without heating systems does not match `Heating Fuel.tsv`, and we are underestimating heating, in some regions (e.g. CR10) potentially up to 20%. This could also be an issue with other fuels, like natural gas, but this needs further investigation to confirm.

Recommendations:
- Completely restructure HVAC TSVs to simplify and ensure that distributions are accurate to source data
- Remove or simplify the dependencies that link distribution of electric heating technologies to cooling saturation
- Add in `resstock_probability` column as standard in all TSVs so that these issues can be identified and diagnosed more quickly
- Compare annual heating totals before and after fix to understand impact of missing heating on old projects.

**Comment by shorowit** [comment] 2020-04-03 17:49
Presumably this occurs because the source data has no samples for the combination of e.g., (heating fuel, climate zone, vintage), right? 

In the past, we had discussions about smoothing probabilities when the sampling is highly granular (@ejhw probably remembers this approach). Alternatively probabilities could filled in using probabilities from nearby combinations that do have samples.

**Comment by joseph-robertson** [comment] 2020-04-03 17:50
I don't think this is a tsv structure issue. If you look at `HVAC System Heating Electricity.tsv`, specifically rows where `Location Region=CR10`, `Vintage=1950s`, `Heating Fuel=Electricity`, `HVAC System Is Heat Pump=No`, and `HVAC System Is Shared=Neither Shared`, you see that the option is 100% `None`.

**Comment by JLReyna** [comment] 2020-04-03 18:02
@joseph-robertson and that's a problem. If we've said `Heating Fuel = Electricity` and not `Heating Fuel =None`, it needs an electric heating technology assigned, but it is not getting any equipment because `Option=None` is 100%  in `HVAC System Heating Electricity.tsv` and it's not getting a shared system or a heat pump. On the row you called out, the `resstock_probability` is 0.1%, so that fraction of the housing stock is not getting electric heating equipment even though it's included in the `Heating Fuel.tsv`

**Comment by joseph-robertson** [comment] 2020-04-03 18:08
I'm confused. So you agree that the `HVAC System Heating Electricity.tsv` file needs to be updated to achieve your desired result? Or you're saying you think there is some other problem?

**Comment by shorowit** [comment] 2020-04-03 18:11
We're in agreement that there's an issue. But the issue is just gaps in the source data, which manifests as gaps in the probability tsv file (like the one that @joseph-robertson pointed to).

**Comment by joseph-robertson** [comment] 2020-04-03 18:56
Hmm. So we didn't *need* to do that then? It was just to make tsvs look nicer?

**Comment by ejhw** [comment] 2020-04-03 20:56
@JLReyna good catch on this. It seems like it got introduced with multifamily capabilities. 

> To me, it's a fundamental issue in the structure if you can allow the assignment of `None` to a building that is supposed to have an electric technology, or maybe that the complexity of the dependency structure masks this happening, but I can see you all are talking about `None` having been the default when no data were available.

In this case, the None is needed for the heat pumps and central shared systems, but maybe there is a better way of structuring that complexity.

**Comment by joseph-robertson** [comment] 2020-09-22 21:39
@JLReyna @afontani does https://github.com/NREL/OpenStudio-BuildStock/pull/478 close this issue? Or should this issue be left open?

**Comment by afontani** [comment] 2020-09-22 21:41
@joseph-robertson: I believe the HVAC restructure does close this issue.

**Comment by joseph-robertson** [comment] 2020-09-24 17:02
Closed in #478.

**Closed by joseph-robertson** 2020-09-24 17:02 UTC
Labels: bug, input data, priority high
